api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "hide-paypal-on-subscriptions"
type = "function"
uid = "463c24e2-5638-c5aa-89ca-cab3eb5588fd616d0f95"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.payment-methods.transform.run"
  input_query = "src/cart_payment_methods_transform_run.graphql"
  export = "cart-payment-methods-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
